#!/usr/bin/env python
# -*- encoding: utf8 -*-

_TXT_ = """やあ （´・ω・｀)

ようこそ、バーボンハウスへ。
このテキーラはサービスだから、まず飲んで落ち着いて欲しい。

うん、「また」なんだ。済まない。
仏の顔もって言うしね、謝って許してもらおうとも思っていない。

でも、このコマンドを実行した時、君は、きっと言葉では言い表せない
「ときめき」みたいなものを感じてくれたと思う。
殺伐とした世の中で、そういう気持ちを忘れないで欲しい
そう思って、このコマンドを作ったんだ。

じゃあ、注文を聞こうか。
"""

def out_words (text):
	import time
	import sys

	for line in text.split("\n"):
		line = unicode(line.decode("utf8"))
		buff = ""
		for w in line:
			print "\r",
			buff += w
			time.sleep(0.06)
			print buff,
			sys.stdout.flush()

		if len (line):
			time.sleep(0.3)
		print "\n",
	# end for line in text.split("\n"):
	return 


if __name__ == '__main__':
	try:
		out_words(_TXT_)
	except:
		pass

